# Generated by Django 3.1.3 on 2020-11-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.TextField()),
                ('ph_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('dev_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('exp', models.TextField()),
                ('cost', models.TextField()),
                ('ph_no', models.CharField(max_length=10)),
                ('service', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Final_bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bid_price', models.IntegerField()),
                ('dev_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('review', models.TextField()),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('domain', models.TextField()),
                ('lvl_exp', models.TextField()),
                ('price_range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PSRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.IntegerField()),
                ('dev_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
