# Generated by Django 3.1.3 on 2020-11-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_id',
            field=models.IntegerField(default=None),
        ),
    ]
