# Generated by Django 3.1.3 on 2020-11-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pass_client',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='developer',
            name='pass_dev',
            field=models.TextField(default=None),
        ),
    ]
