# Generated by Django 3.1.3 on 2020-11-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0002_auto_20201127_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='psrecord',
            name='dev_name',
            field=models.TextField(default=None),
        ),
    ]
