# Generated by Django 3.1.3 on 2020-11-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0003_psrecord_dev_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='dev_selected_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='proj_selected_flag',
            field=models.IntegerField(default=0),
        ),
    ]
