# Generated by Django 3.1.3 on 2020-11-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0004_auto_20201130_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_bid',
            name='date',
            field=models.TextField(),
        ),
    ]
