# Generated by Django 3.1.3 on 2020-11-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0008_auto_20201130_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_bid',
            name='date',
        ),
    ]
