# Generated by Django 3.1.3 on 2020-11-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0009_remove_final_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_selected_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='developer',
            name='dev_selected_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_selected_flag',
            field=models.BooleanField(default=False),
        ),
    ]
