# Generated by Django 3.1.3 on 2020-11-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0010_auto_20201130_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_selected_flag',
        ),
    ]
