# Generated by Django 3.1.3 on 2020-12-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0011_remove_client_client_selected_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_bid',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
